In [1]:
# Configure Jupyter so figures appear in the notebook
%matplotlib inline

# Configure Jupyter to display the assigned value after an assignment
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'

# import functions from the modsim.py module
from modsim import *


# import libraries
# (these may or may not be necessary)

import matplotlib.pyplot as plt

import numpy as np
from numpy.linalg import eig
from numpy.linalg import inv

In [2]:
a = np.array([[0.9947, 0.0003, 0.0007, 0.0003], 
              [0.0006, 0.9962, 0.0019, 0.0011],
              [0.0025, 0.0032, 0.9942, 0.0118],
              [0.0022, 0.0003, 0.0032, 0.9868]]) #transition matrix of the resident movements converted into decimals

a = np.linalg.matrix_power(a,100) #raises the matrix a to the power of 100 to approximate the limiting matrix

array([[0.59721457, 0.02715819, 0.04727733, 0.03414208],
       [0.06477595, 0.70688367, 0.13619282, 0.10919146],
       [0.22191297, 0.22394799, 0.67362491, 0.51857762],
       [0.11609651, 0.04201014, 0.14290494, 0.33808884]])

In [3]:
w,v=eig(a)
print('E-value:', w)
print('E-vector matrix', v)  #each matrix COLUMN is an eigenvector corresponding to the eigenvalue list, in order

E-value: [1.         0.18625627 0.52870252 0.60085321]
E-vector matrix [[-0.14986748  0.02689803  0.38638656 -0.2892182 ]
 [-0.50126994  0.05173857  0.53344662  0.85892275]
 [-0.81918362 -0.74412599 -0.72739892 -0.37519302]
 [-0.23496038  0.66548939 -0.19243426 -0.19451153]]


In [4]:
evector=v[:,0:1] #rows 0 through 1, column 1; returns a column vector

array([[-0.14986748],
       [-0.50126994],
       [-0.81918362],
       [-0.23496038]])

In [5]:
evector = evector/sum(evector) #limiting matrix

array([[0.08788431],
       [0.29395145],
       [0.48038031],
       [0.13778393]])

In [6]:
np.linalg.matrix_power(a,100)

array([[0.08788431, 0.08788431, 0.08788431, 0.08788431],
       [0.29395145, 0.29395145, 0.29395145, 0.29395145],
       [0.48038031, 0.48038031, 0.48038031, 0.48038031],
       [0.13778393, 0.13778393, 0.13778393, 0.13778393]])